name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./**/node_modules
            ./**/yarn.lock
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile
          yarn compile

      - name: Get version
        id: package
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package.outputs.version }}
          release_name: Release ${{ steps.package.outputs.version }}
          draft: false
          prerelease: false

      - name: Install vsce
        run: npm install -g vsce

      - name: Check if VSCE_TOKEN is set
        run: |
          if [[ -z "${VSCE_TOKEN}" ]]; then
            echo "VSCE_TOKEN is empty"
            exit 1
          else
            echo "VSCE_TOKEN is not empty"
          fi
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
